help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

setup: ## Setup conda environment using the setup script
	chmod +x scripts/create_env.sh
	./scripts/create_env.sh

test: ## Run all quantization tests
	python src/test_quantization.py

ptq: ## Run multi-bitwidth PTQ (recommended)
	python src/ptq_quantize.py --data_path data/ --max_eval_batches 10

ptq-aimet: ## Run AIMET + Power-of-2 PTQ example (professional)
	python src/aimet_power_of_2_ptq.py --data_path data/ --max_eval_batches 10

qat: ## Run multi-bitwidth QAT with PTQ init (recommended)
	python src/qat_train.py --data_path data/ --epochs 2

qat-full: ## Run full QAT training (10 epochs)
	python src/qat_train.py --data_path data/ --epochs 10

qat-aimet: ## Run AIMET + Power-of-2 QAT example (2 epochs)
	python src/aimet_power_of_2_qat.py --data_path data/ --epochs 2

demo: ## Run power-of-2 quantizer demonstration
	python src/utils/power_of_2_quantizer.py

clean: ## Clean autogenerated files (excluding quantization outputs)
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-outputs: ## Remove all quantization output files
	@echo "Removing quantization output files..."
	rm -rf quantized_outputs/
	rm -rf qat_outputs/
	rm -rf aimet_power_of_2_outputs/
	rm -rf aimet_power_of_2_qat_outputs/
	rm -rf outputs/
	@echo "Quantization output files removed"

clean-data: ## Remove downloaded dataset files
	@echo "Removing downloaded dataset files..."
	rm -rf data/cifar-10-batches-py/
	rm -f data/cifar-10-python.tar.gz
	@echo "Dataset files removed"

clean-all: clean clean-outputs clean-data ## Clean everything (autogenerated files and all outputs)
	@echo "All generated files cleaned"

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

.PHONY: help setup test ptq ptq-aimet qat qat-full qat-aimet demo clean clean-outputs clean-data clean-all sync
